name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Commands to Deploy
        uses: appleboy/ssh-action@master
        with:
          # These 3 MUST be created as separate New Repository Secrets
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          port: ${{ secrets.HOSTINGER_PORT }}
          # Using the secret name you created in your screenshot
          password: ${{ secrets.CABMANAGER_SECRET }}
          script: |
            cd domains/abdulajij.in/public_html/cabmanager
            git pull origin main
            composer update --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan optimize:clear